# Generated by Django 5.0.10 on 2025-01-14 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pet_Cus_Info_Mng', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('status', models.CharField(choices=[('pending', 'Đang chờ xử lý'), ('completed', 'Đã hoàn thành xong')], max_length=50)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pet_Cus_Info_Mng.customer')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pet_Cus_Info_Mng.pet')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('treatment_details', models.TextField()),
                ('doctor', models.CharField(max_length=255)),
                ('remarks', models.TextField()),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pet_Cus_Info_Mng.pet')),
            ],
        ),
    ]
