# Generated by Django 5.0.10 on 2025-01-15 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pet_Cus_Info_Mng', '0002_appointment_medicalrecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='customer',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(default='default@gmail.com', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='firstName',
            field=models.CharField(default='Default First Name', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='lastName',
            field=models.CharField(default='Default Last Name', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='phoneNumber',
            field=models.CharField(default='0123456789', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.CharField(choices=[('Male', 'Nam'), ('Female', 'Nữ'), ('Other', 'Khác')], max_length=10),
        ),
        migrations.AlterField(
            model_name='customer',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='Pet_Cus_Info_Mng.pet'),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='health_status',
            field=models.CharField(choices=[('hospitalized', 'Đang nhập viện'), ('outpatient', 'Đang điều trị ngoại trú'), ('discharged', 'Đã xuất viện')], max_length=50),
        ),
    ]
