# Generated by Django 5.0.10 on 2025-01-15 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pet_Cus_Info_Mng', '0003_remove_customer_name_remove_customer_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='age',
            field=models.PositiveIntegerField(default=18),
            preserve_default=False,
        ),
    ]
