# Generated by Django 5.0.10 on 2025-01-18 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pet_Cus_Info_Mng', '0006_alter_customer_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='date_of_birth',
            new_name='dateOfBirth',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='health_status',
        ),
        migrations.AddField(
            model_name='pet',
            name='healthStatus',
            field=models.CharField(choices=[('Đang nhập viện', 'Đang nhập viện'), ('Đang điều trị ngoại trú', 'Đang điều trị ngoại trú'), ('Đã xuất viện', 'Đã xuất viện'), ('Sức khỏe tốt', 'Sức khỏe tốt'), ('Cần tiêm phòng', 'Cần tiêm phòng'), ('Béo phì', 'Béo phì'), ('Bị chấn thương', 'Bị chấn thương'), ('Dinh dưỡng kém', 'Dinh dưỡng kém'), ('Giai đoạn cuối', 'Giai đoạn cuối')], default='Đang điều trị ngoại trú', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pet',
            name='gender',
            field=models.CharField(choices=[('Đực', 'Đực'), ('Cái', 'Cái')], max_length=10),
        ),
    ]
