# Generated by Django 5.0.10 on 2025-01-22 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pet_Cus_Info_Mng', '0008_rename_treatment_details_medicalrecord_treatmentdetails_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Đang chờ xử lý'), ('completed', 'Đã hoàn thành')], max_length=50),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
