# Generated by Django 5.0.10 on 2025-01-24 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pet_Cus_Info_Mng', '0009_alter_appointment_status_alter_customer_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
