# Generated by Django 5.0.10 on 2025-01-24 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pet_Cus_Info_Mng', '0010_delete_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Chưa thanh toán'), ('completed', 'Đã thanh toán')], max_length=50),
        ),
    ]
