version: '3.4'

services:
  cnpmprojectid21:
    image: cnpmprojectid21
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 Nhom_4_ID_21\Pet_Health_Care_System runserver 0.0.0.0:9000 --nothreading --noreload"]
    ports:
      - 9000:9000
      - 5678:5678
