# Generated by Django 5.0.11 on 2025-02-11 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='current_occupancy',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('Standard', 'Standard'), ('Luxury', 'Luxury'), ('Indoor', 'Indoor'), ('Outdoor', 'Outdoor'), ('Quarantine', 'Quarantine'), ('Recovery', 'Recovery'), ('Training', 'Training'), ('Breeding', 'Breeding'), ('Large', 'Large Animal'), ('Custom', 'Customizable')], default='Standard', max_length=20),
        ),
    ]
