# Generated by Django 4.2.18 on 2025-02-11 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pet_Health_CheckUp_Treatment_Prg', '0002_medicalrecord_notes_notification_medication_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreatmentProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatment_method', models.TextField()),
                ('next_appointment_date', models.DateField(blank=True, null=True)),
                ('updated_health_status', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='treatment',
            name='pet',
        ),
        migrations.RenameField(
            model_name='medicalrecord',
            old_name='consultation_date',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='medication',
            name='dosage',
        ),
        migrations.RemoveField(
            model_name='medication',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='medication',
            name='frequency',
        ),
        migrations.RemoveField(
            model_name='medication',
            name='medication_name',
        ),
        migrations.RemoveField(
            model_name='medication',
            name='pet',
        ),
        migrations.RemoveField(
            model_name='medication',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='notification_date',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='type',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='breed',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='health_status',
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='vet_notes',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='medication',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medication',
            name='dosage_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medication',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='sent_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='current_health_status',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='species',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='disease',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='Pet_Health_CheckUp_Treatment_Prg.pet'),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='symptoms',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='Pet_Health_CheckUp_Treatment_Prg.pet'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='age',
            field=models.PositiveIntegerField(),
        ),
        migrations.DeleteModel(
            name='MedicalHistory',
        ),
        migrations.DeleteModel(
            name='Treatment',
        ),
        migrations.AddField(
            model_name='treatmentprogress',
            name='medical_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treatment_progress', to='Pet_Health_CheckUp_Treatment_Prg.medicalrecord'),
        ),
        migrations.AddField(
            model_name='treatmentprogress',
            name='medication',
            field=models.ManyToManyField(blank=True, to='Pet_Health_CheckUp_Treatment_Prg.medication'),
        ),
        migrations.AddField(
            model_name='treatmentprogress',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatment_progress', to='Pet_Health_CheckUp_Treatment_Prg.pet'),
        ),
    ]
