# Generated by Django 4.2.18 on 2025-02-11 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pet_Health_CheckUp_Treatment_Prg', '0003_treatmentprogress_remove_treatment_pet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
